name: yolov3
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.3
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=3.3.0
  - python=3.9.19
  - readline=8.2
  - tk=8.6.13
  - tzdata=2024a
  - xz=5.2.6
  - pip:
      - absl-py==1.3.0
      - asttokens==2.4.1
      - build==1.2.1
      - cachecontrol==0.14.0
      - cachetools==5.2.0
      - certifi==2022.9.24
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - cleo==2.1.0
      - comm==0.2.2
      - contourpy==1.0.6
      - crashtest==0.4.1
      - cryptography==42.0.7
      - cycler==0.11.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - distlib==0.3.8
      - dulwich==0.21.7
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - fonttools==4.38.0
      - google-auth==2.14.0
      - google-auth-oauthlib==0.7.1
      - grpcio==1.53.0
      - idna==3.4
      - imageio==2.22.3
      - imgaug==0.4.0
      - importlib-metadata==5.0.0
      - installer==0.7.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - jaraco-classes==3.4.0
      - jedi==0.19.1
      - jeepney==0.8.0
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - keyring==24.3.1
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.7
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - numpy==1.23.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - opencv-python==4.6.0.66
      - packaging==23.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==9.3.0
      - pip==23.3.1
      - pkginfo==1.10.0
      - platformdirs==4.2.2
      - poetry==1.8.3
      - poetry-core==1.9.0
      - poetry-plugin-export==1.8.0
      - profilehooks==1.12.0
      - prompt-toolkit==3.0.43
      - protobuf==3.19.6
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.0.9
      - pyproject-hooks==1.1.0
      - python-dateutil==2.8.2
      - pytorchyolo==1.8.0
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - rapidfuzz==3.9.1
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - scikit-image==0.19.3
      - scipy==1.9.3
      - secretstorage==3.3.3
      - setuptools==65.5.1
      - shapely==1.8.5.post1
      - shellingham==1.5.4
      - six==1.16.0
      - stack-data==0.6.3
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - terminaltables==3.1.10
      - tifffile==2021.11.2
      - tomli==2.0.1
      - tomlkit==0.12.5
      - torch==1.13.0
      - torchaudio==0.13.0
      - torchsummary==1.5.1
      - torchvision==0.14.0
      - tornado==6.4
      - tqdm==4.64.1
      - traitlets==5.14.3
      - trove-classifiers==2024.5.17
      - typing-extensions==4.4.0
      - urllib3==1.26.13
      - virtualenv==20.26.2
      - wcwidth==0.2.13
      - werkzeug==2.2.3
      - wheel==0.38.1
      - zipp==3.10.0
